// <auto-generated />
using DnD_Archive.Models.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DnD_Archive.Migrations
{
    [DbContext(typeof(DbManager))]
    [Migration("20240430072732_Character")]
    partial class Character
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("DnD_Archive.Models.CharInfo", b =>
                {
                    b.Property<int>("InfoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InfoID"));

                    b.Property<string>("AdditionalInfo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bonds")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Flaws")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ideals")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("personalitTraits")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InfoID");

                    b.ToTable("charInfos");
                });

            modelBuilder.Entity("DnD_Archive.Models.CharStat", b =>
                {
                    b.Property<int>("StatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("StatId"));

                    b.Property<int>("Charisma")
                        .HasColumnType("int");

                    b.Property<int>("Constitution")
                        .HasColumnType("int");

                    b.Property<int>("Dexterity")
                        .HasColumnType("int");

                    b.Property<int>("Intelligence")
                        .HasColumnType("int");

                    b.Property<int>("ProficiencyBonus")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL1")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL2")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL3")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL4")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL5")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL6")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL7")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL8")
                        .HasColumnType("int");

                    b.Property<int>("SpellSlotsLVL9")
                        .HasColumnType("int");

                    b.Property<int>("Strength")
                        .HasColumnType("int");

                    b.Property<int>("Wisdom")
                        .HasColumnType("int");

                    b.HasKey("StatId");

                    b.ToTable("charStats");
                });

            modelBuilder.Entity("DnD_Archive.Models.CharacterSheet", b =>
                {
                    b.Property<int>("SheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SheetId"));

                    b.Property<string>("CharName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.HasKey("SheetId");

                    b.HasIndex("UserID");

                    b.ToTable("CharacterSheets");
                });

            modelBuilder.Entity("DnD_Archive.Models.Inventory", b =>
                {
                    b.Property<int>("InventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("InventoryId"));

                    b.Property<string>("Additonal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Copper")
                        .HasColumnType("int");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<string>("Items")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Platin")
                        .HasColumnType("int");

                    b.Property<int>("Silver")
                        .HasColumnType("int");

                    b.Property<string>("Weapons")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("InventoryId");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("DnD_Archive.Models.Spells", b =>
                {
                    b.Property<int>("SpellsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("SpellsId"));

                    b.Property<int>("CharacterSheetSheetId")
                        .HasColumnType("int");

                    b.Property<string>("SpellAbility")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SpellDamage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SpellLvl")
                        .HasColumnType("int");

                    b.Property<string>("SpellName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("SpellsId");

                    b.HasIndex("CharacterSheetSheetId");

                    b.ToTable("SpellList");
                });

            modelBuilder.Entity("DnD_Archive.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DnD_Archive.Models.CharacterSheet", b =>
                {
                    b.HasOne("DnD_Archive.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DnD_Archive.Models.Spells", b =>
                {
                    b.HasOne("DnD_Archive.Models.CharacterSheet", "CharacterSheet")
                        .WithMany()
                        .HasForeignKey("CharacterSheetSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CharacterSheet");
                });
#pragma warning restore 612, 618
        }
    }
}
